timescale:
  image: timescale/timescaledb-postgis:0.12.1-pg10
  environment:
    - "POSTGRES_USER=zoo_stats"
    - "POSTGRES_PASSWORD=zoo_stats"
  ports:
    - "5432"

gem_cache:
  image: busybox
  volumes:
    - /gem_cache

zoo_stats:
  dockerfile: Dockerfile
  build: ./
  volumes:
    - ./:/rails_app
  volumes_from:
    - gem_cache
  ports:
    - "3000:3000"
  environment:
    - "RAILS_ENV=development"
    - "BUNDLE_PATH=/gem_cache"
    - "BUNDLE_BIN=/gem_cache/bin"
    - "DISABLE_SPRING=true"
  links:
    - timescale:db